image:
  file: .gitpod.Dockerfile
ports:
- port: 8000
  onOpen: open-preview
- port: 6080
  onOpen: open-preview
tasks:
- init: >
        pyenv install 3.6.4 &&
        pyenv global 3.6.4 &&
        chmod +x envconfig.sh &&
        bash envconfig.sh 
        
